package io.github.vankorno.txtfield._data.vpravy.difficulties


fun DiffTypingUnits.lvl5() = arrayOf( // Capitalized, Enter, high text complexity
    "Mitochondria are often referred to as the 'powerhouses' of the cell because they generate most of the cell's supply of adenosine triphosphate (ATP), which is used as a source of chemical energy.",
    "In computer science, a binary tree is a data structure in which each node has at most two children, referred to as the left child and the right child.",
    "Stress management techniques such as deep breathing exercises, meditation, and regular physical activity can help improve overall well-being and reduce the negative effects of chronic stress.",
    "The Great Wall of China stretches over approximately 13,170 miles (21,196 kilometers) and was built over several centuries to protect China from invasions by nomadic tribes.",
    "According to the theory of evolution, species gradually change over time through the process of natural selection, where individuals with advantageous traits are more likely to survive and reproduce.",
    "Plants undergo photosynthesis, a process in which they convert carbon dioxide and water into glucose and oxygen using sunlight as the source of energy.",
    "Learning a new language has been shown to have numerous cognitive benefits, including improved memory, problem-solving skills, and multitasking abilities.",
    "Procrastination can often be overcome by breaking tasks into smaller, more manageable steps and setting specific, achievable goals.",
    "Renaissance art is characterized by a focus on realism, humanism, and perspective, with artists such as Leonardo da Vinci and Michelangelo making significant contributions to the period.",
    "Volcanoes are formed when magma from within the Earth's mantle erupts through the surface, releasing gases, lava, and volcanic ash.",
    "Regular exercise not only improves physical health but also has been linked to reduced symptoms of depression and anxiety, as well as improved mood and overall well-being.",
    "The human brain is composed of approximately 86 billion neurons, each forming connections with thousands of other neurons to transmit electrical signals and process information.",
    "In psychology, cognitive-behavioral therapy (CBT) is a widely used treatment approach that focuses on changing patterns of thinking and behavior to alleviate symptoms of various mental health disorders.",
    "Plate tectonics is the scientific theory that describes the movement of the Earth's lithosphere, which is divided into several large and small plates that float on the semi-fluid asthenosphere beneath them.",
    "The Earth's atmosphere is composed of approximately 78% nitrogen, 21% oxygen, and trace amounts of other gases.",
    "Water covers approximately 71% of the Earth's surface, with the majority found in oceans, seas, and other bodies of water.",
    "The human body is composed of approximately 60% water, which is essential for various physiological processes such as digestion, circulation, and temperature regulation.",
    "In physics, Newton's laws of motion describe the relationship between an object's motion and the forces acting upon it, with the first law stating that an object will remain at rest or in uniform motion unless acted upon by an external force.",
    "Biodiversity refers to the variety of life forms on Earth, including species diversity, genetic diversity, and ecosystem diversity, which are all interconnected and play a crucial role in maintaining ecological balance.",
    "Climate change is driven by human activities such as the burning of fossil fuels, deforestation, and industrial processes, leading to an increase in global temperatures, rising sea levels, and more frequent extreme weather events.",
    "Genetic engineering techniques such as CRISPR-Cas9 have revolutionized the field of biotechnology, allowing scientists to modify DNA with precision and potentially treat genetic diseases, develop new therapies, and improve crop yields.",
    "Critical thinking skills are essential for analyzing information, evaluating arguments, and making informed decisions in various aspects of life, including education, work, and everyday situations.",
    "The Industrial Revolution, which began in the late 18th century, transformed societies from agrarian economies to industrialized nations through technological advancements such as the steam engine, mechanized manufacturing, and urbanization.",
    "Human rights are universal rights inherent to all individuals, regardless of race, nationality, religion, or other characteristics, and are protected by international law and treaties.",
    "The scientific method is a systematic approach to inquiry that involves making observations, formulating hypotheses, conducting experiments, analyzing data, and drawing conclusions to test and refine scientific theories.",
    "Artificial intelligence (AI) refers to the development of computer systems capable of performing tasks that typically require human intelligence, such as speech recognition, decision-making, and problem-solving.",
    "Climate change mitigation strategies include reducing greenhouse gas emissions, transitioning to renewable energy sources, increasing energy efficiency, and implementing policies to protect ecosystems and promote sustainable development.",
    "The human genome consists of approximately 3 billion base pairs of DNA, which contain the instructions for building and maintaining an individual's unique traits and characteristics.",
    "Psychological resilience refers to the ability to adapt and bounce back from adversity, trauma, or significant life stressors, and can be cultivated through social support, coping strategies, and positive thinking.",
    "Sociocultural factors such as socioeconomic status, education, ethnicity, and cultural norms influence health outcomes and disparities, including access to healthcare, disease prevalence, and treatment outcomes.",
    "The Theory of Relativity, proposed by Albert Einstein in the early 20th century, revolutionized our understanding of space, time, and gravity.",
    "Renewable energy sources such as solar, wind, and hydroelectric power offer sustainable alternatives to fossil fuels, reducing greenhouse gas emissions and mitigating climate change.",
    "Stem cells are undifferentiated cells with the potential to develop into various cell types in the body, making them valuable for medical research and regenerative therapies.",
    "The Hubble Space Telescope, launched in 1990, has provided astronomers with unprecedented views of distant galaxies, nebulae, and other celestial objects, expanding our knowledge of the universe.",
    "Urbanization, the process of population concentration in cities, has led to significant social, economic, and environmental changes, including increased pollution, infrastructure demands, and cultural diversity.",
    "The human digestive system consists of various organs, including the stomach, small intestine, and large intestine, which work together to break down food, absorb nutrients, and eliminate waste.",
    "Cultural globalization refers to the interconnectedness and exchange of ideas, values, and practices across different cultures, facilitated by advances in communication, transportation, and technology.",
    "The greenhouse effect is a natural process that warms the Earth's surface by trapping heat in the atmosphere, but human activities have intensified this effect, leading to global warming and climate change.",
    "Microorganisms such as bacteria, viruses, and fungi play essential roles in ecosystems, including nutrient cycling, decomposition, and symbiotic relationships with plants and animals.",
    "Financial literacy involves understanding various financial concepts and principles, such as budgeting, investing, and managing debt, to make informed decisions about money and achieve financial goals.",
    "Maslow's hierarchy of needs is a psychological theory that suggests humans are motivated by a hierarchy of needs, including physiological, safety, belongingness, esteem, and self-actualization.",
    "Blockchain technology, best known for its use in cryptocurrencies like Bitcoin, is a decentralized digital ledger that securely records transactions and data across multiple computers.",
    "The human respiratory system includes organs such as the lungs, trachea, and bronchi, which facilitate the exchange of oxygen and carbon dioxide between the body and the environment.",
    "Environmental sustainability involves meeting the needs of the present generation without compromising the ability of future generations to meet their own needs, through responsible resource management and conservation.",
    "Artificial ecosystems, such as aquaponics and terrariums, mimic natural ecosystems to support plant growth, nutrient cycling, and biodiversity in controlled environments.",
    "The Great Wall of China is the longest wall in the world, stretching over approximately 13,170 miles (21,196 kilometers).",
    "The Nile River is the longest river in the world, spanning about 4,135 miles (6,650 kilometers) in length.",
    "The ancient city of Rome was founded in 753 BCE and eventually grew into one of the largest and most powerful empires in history.",
    "The largest empire in history, the Mongol Empire, was established by Genghis Khan in the 13th century and spanned across Asia, Europe, and the Middle East.",
    "The Battle of Waterloo, fought on June 18, 1815, marked the final defeat of Napoleon Bonaparte and the end of the Napoleonic Wars.",
    "The Berlin Wall, constructed in 1961 to divide East and West Berlin during the Cold War, stood for 28 years before its eventual collapse in 1989.",
    "The ancient city of Pompeii was buried under volcanic ash and pumice during the eruption of Mount Vesuvius in 79 CE, preserving its ruins for centuries.",
    "The Silk Road was a network of trade routes that connected the East and West, facilitating the exchange of goods, ideas, and cultures between Asia, Europe, and Africa.",
    "The Industrial Revolution, which began in the late 18th century in Britain, transformed societies from agrarian economies to industrialized nations through technological advancements in manufacturing and transportation.",
    "The Seven Wonders of the Ancient World were a collection of remarkable structures including the Great Pyramid of Giza, the Hanging Gardens of Babylon, and the Statue of Zeus at Olympia.",
    "The Panama Canal, completed in 1914, is a man-made waterway that connects the Atlantic and Pacific Oceans, allowing ships to bypass the lengthy journey around the southern tip of South America.",
    "The Cold War was a period of geopolitical tension between the United States and the Soviet Union from the late 1940s to the early 1990s, characterized by ideological, economic, and military rivalry.",
    "The British Empire was the largest empire in history, spanning territories across six continents at its height in the 1920s.",
    
    //"Moskovy (so called russia) is an imperialistic totalitarian regime that tries to corrupt, destabilize, or even destroy neighboring democracies.",
    //"Russian schizo-fascists love using whataboutism in order to rationalize their own crimes.",
    
)
