package io.github.vankorno.txtfield._data.vpravy.difficulties


fun DiffTypingUnits.lvl2() = arrayOf( // 3-5 words + some secondary letters
    "night in the city",
    "lost in the forest",
    "code error detected",
    "a silent dream",
    "heard a loud crash",
    "rain on the roof",
    "the dance floor",
    "climb higher",
    "a tired dog",
    "shine bright",
    "a cool drink",
    "under the tree",
    "a hidden treasure",
    "close the window",
    "a hot summer day",
    "write a letter",
    "the ancient relic",
    "silent night",
    "a clear choice",
    "the hard drive",
    "inside the cave",
    "a distant shore",
    "learn to dance",
    "the secret code",
    "a new horizon",
    "open the door",
    "the wild horse",
    "a cold winter night",
    "start the engine",
    "hidden treasure chest",
    "the dark forest",
    "a lost cause",
    "a sad bad sadist",
    "crash course",
    "drive carefully",
    "a silent prayer",
    "she has a dream",
    "lions and cats roared",
    "that red dodo is here",
    "that dlc is not done",
    "hot indoors cold indoors",
    "a cat is on the tree",
    "the cat stares at me",
    "she hates red hats and dresses",
    "it can contain these letters",
    "he can read notes",
    "she is here he is there",
    "she does that he does that",
    "he lies to them",
    "notion potion promotion",
    "do not go there",
    "one man did that",
    "he was ready for that",
    "where is that cat",
    "what is your name",
    "send your photo and papers",
    "not at the moment",
    "the current situation",
    "the current trends",
    "our current location",
    "we have to do it",
    "you have to do it",
    "raiders are coming",
    "plan some activities",
    "to reach our destination",
    "stop at several stations",
    "not at that station",
    "the train will stop at that station",
    "mom and dad went mad",
    "the more the better",
    "no more running around",
    "he does not understand",
    "we understand it",
    "did you hear that",
    "they got it from there",
    "open and close the doors",
    "do not go around the wall",
    "this story is interesting",
    "stranger danger",
    "long story short",
    "five dollars each",
    "the dragon from the story",
    "the dodo is his only friend",
    "this version is not new",
    "stand and fight at night",
    "our dlc is released",
    "about our research", 
    "scientists research that",
    "training is important",
    "something important",
    "more or less the same as",
    "it lasts more or less five hours",
    "more or less accurate",
    "never lie to me",
    "somebody has something",
    "time for me to go",
    "they see you and me",
    "they cannot count",
    "positive vibes",
    "we are so happy",
    "do not fear me",
    "this is not for us",
    "a present for you",
    "you should sleep at night",
    "have some silver and gold",
    "team number seven",
    "four turtles killed a crocodile",
    "was deserted a long time ago",
    "on that derelict ship",
    "do not touch the alligator",
    "a soldier is ready to attack",
    "you shall not pass",
    "the dude has no guts",
    "today or tomorrow",
    "it sounds good",
    "sounds too good to be true",
    "try to steer it in a new direction",
    "they have no money",
    "the consent of the landlord",
    
)