package io.github.vankorno.txtfield._data.vpravy.difficulties


fun DiffTypingUnits.lvl3() = arrayOf( // All letters, some symbols, sometimes capitalized
    "the sun shines bright over green fields",
    "birds sing melodies in the morning",
    "trees sway gently in the breeze",
    "water flows calmly downstream",
    "people walk along busy city streets",
    "cars zoom past on highways",
    "children play joyfully in parks",
    "dogs bark loudly in the distance",
    "cats purr softly when petted",
    "food tastes delicious when cooked well",
    "music sounds soothing to the ears",
    "books offer knowledge and escape",
    "movies entertain with drama and action",
    "friends laugh together at jokes",
    "love blooms between two hearts",
    "work occupies most of our days",
    "sleep rejuvenates the weary soul",
    "dreams transport us to other worlds",
    "rain falls gently on the roof",
    "snow blankets the ground in winter",
    "stars twinkle in the night sky",
    "clouds float lazily overhead",
    "computers hum with activity all day",
    "internet connects us to the world",
    "games provide hours of entertainment",
    "sports bring people together in competition",
    "art inspires creativity and imagination",
    "nature amazes with its beauty and diversity",
    "life is a journey full of ups and downs",
    "the sun shines bright over green fields",
    "birds sing melodies in the morning",
    "they soar high in the sky",
    "water flows calmly downstream",
    "people walk along busy city streets",
    "we all have dreams to pursue",
    "cars zoom past on highways",
    "they carry passengers to destinations",
    "children play joyfully in parks",
    "dogs bark loudly in the distance",
    "cats purr softly when petted",
    "food tastes delicious when cooked well",
    "music sounds soothing to the ears",
    "books offer knowledge and escape",
    "movies entertain with drama and action",
    "friends laugh together at jokes",
    "love blooms between two hearts",
    "work occupies most of our days",
    "sleep rejuvenates the weary soul",
    "dreams transport us to other worlds",
    "rain falls gently on the roof",
    "snow blankets the ground in winter",
    "stars twinkle in the night sky",
    "clouds float lazily overhead",
    "phones buzz with notifications constantly",
    "computers hum with activity all day",
    "internet connects us to the world",
    "games provide hours of entertainment",
    "sports bring people together in competition",
    "art inspires creativity and imagination",
    "nature amazes with its beauty and diversity",
    "I'm so tired, I could sleep for days.",
    "You're not making any sense.",
    "I can't believe you said that!",
    "we need to talk about this later",
    "I'm running late, as usual.",
    "don't forget to pick up some milk",
    "I'm not in the mood for your jokes",
    "Can you please pass the salt?",
    "I have a lot on my plate right now.",
    "I didn't mean to hurt your feelings.",
    "let's just agree to disagree",
    "stop interrupting me when I'm speaking",
    "Can you help me with this, please?",
    "I'm not sure if they can make it in time.",
    "I'm really looking forward to the weekend.",
    "We'll figure it out together.",
    "he needs some time alone to think",
    "I'm really proud of you!",
    "everything will be okay in the end",
    "I'm not going to let you down.",
    "I can't believe how fast time flies!",
    "the quick brown fox jumps over the lazy dog",
    "the five boxing wizards jump quickly",
    "pack my box with five dozen liquor jugs",
    "my sister makes a lot of money",
    "they always worry about taxes",
    "not my circus, not my monkeys",
    "back to the future",
    "definitely not my cup of tea",
)
