package io.github.vankorno.txtfield._data.vpravy.difficulties

class DiffTypingUnits() {
    fun lvl1() = arrayOf( // 1-3 words, most frequent letters
        "it is not",
        "to do or not to do",
        "she does not",
        "he did not",
        "not to do",
        "the tall tree",
        "these cats",
        "it is in there",
        "on that street",
        "there is a car",
        "there are",
        "lions roar",
        "a red cat",
        "a red car",
        "into the car",
        "his dad",
        "her dad",
        "the dodo",
        "it is cool",
        "it is there",
        "it is not",
        "a cat stares",
        "he ran into",
        "than that",
        "her notes",
        "he hates rain",
        "in the rain",
        "red lines",
        "to stare at",
        "cross the line",
        "an old tree",
        "on the tree",
        "her dresses",
        "his old hat",
        "hat on his head",
        "it is done",
        "it is not done",
        "done deal",
        "distance",
        "distinct",
        "three dots",
        "three notes",
        "one death",
        "a sonnet",
        "dot net",
        "no internet",
        "he cries",
        "their nation",
        "in the sea",
        "on the road",
        "at his side",
        "it is a lot",
        "are indoors",
        "hold the door",
        "old stone",
        "that node",
        "hide inside",
        "do not die",
        "not at all",
        "not at that",
        "honest trailer",
        "old throne",
        "dead horse",
        "has no idea",
        "on her date",
        "it is late",
        "not too late",
        "he is late",
        "hot indoors",
        "it is hot",
        "to create",
        "to declare",
        "not to care",
        "his and her son",
        "a condition",
        "lions are cats",
        "it is done",
        "the red star",
        "land and sea",
        "ironic hate",
        "last sensei",
        "not alone",
        "too dramatic",
        "ancient coin",
        "read notes",
        "can he dance",
        "cannot do",
        "cannot see",
        "he can read",
        "a sad hero",
        "iconic roles",
        "hand and ear",
        "cold hands",
        "coastal line",
        "northern road",
        "toss a coin",
        "she hates it",
        "hates horses",
        "ride a horse",
        "it contains",
        "lead dancer",
        "are not here",
        "are not done",
        "he or she did",
        "here or there",
        "it is a deal",
        "dear son",
        "not a hero",
        "cold heart",
        "cold rain",
        "hot star",
        "at the core",
        "one dollar",
        "on a train",
        "lost herd",
        "not a loser",
        "in order to",
        "tired healer",
        "rich dealer",
        "one drone",
        "ears hear",
        "clean hair",
        "hairdresser",
        "dead hare",
        "cannot stand",
        "had to do",
        "has to share",
        "does not care",
        "not so cool",
        "has to search",
        "at school",
        "thirteen",
        "nineteen",
        "nine liters",
        "nine chairs",
        "one dose",
        "three dolls",
        "cold rice",
        "not nice",
        "that is nice",
        "roll the dice",
        "rise and shine",
        "taste this",
        "not a test",
        "hard test",
        "can relate",
        "he dines there",
        "he dares",
        "stand and cheer",
        "not realistic",
        "on a scale",
        "send a letter",
        "a lost letter",
        "shaders",
        "so talented",
        "lost nest",
        "need to do",
        "there is",
        "there are",
        "here it is",
        "learn it",
        "can learn",
        "had to sell",
        "their clinic",
        "on earth",
        "not tired",
        "hold it there",
        "teach at school",
        "honest teacher",
        "not solid",
        "not ideal",
        "not historic",
        "stand still",
        "northern shore",
        "is isolated",
        "are sincere",
        "has reached",
        "has an idea",
        "sit or dance",
        "strict or not",
        "one host",
        "it is total",
        "no stress",
        "the last ride",
        "had it all",
        "he has a tie",
        "not that one",
        "neither nor",
        "it rolls",
        "not hard",
        "sore throat",
        "con artist",
        "other hand",
        "old trenches",
        "an old case",
        "in this case",
        "real cost",
        "on the ladder",
        "ar old rat",
        "has looted",
        "she stood there",
        "a lone lion",
        "a dancer dances",
        "a tall tree",
        "it is inside",
        "it is sad",
        "he is not sad",
        "easier than",
        "that direction",
        "a thin red line",
        "the old road",
        "his dad hit her dad",
        "the iron door",
        "the lion roared",
        "old lions roared",
        "not his red car",
        "the less he does",
        "this is science",
        "her training",
        "a liar lies",
        "cannot read",
        "nine toilets",
        "crocodile island",
        "she shoots at it",
        "he and she are there",
        "it is so odd",
        "are not tired",
        "a loose tire",
        "to steer clear",
        "on old school",
        "school classes",
        "school lessons",
        "to learn a lesson",
        "stand in class ???",
        "dread thread",
        "his lesson ended",
        "see instead",
        "he needs her",
        "install that",
        "it is installed",
        "the installer",
        "he sees no cats",
        "on the corner",
        "across the street",
        "her dolls and cars",
        "he cannot see",
        "a short riddle",
        "shorten it",
        "not so soon",
        "a real doctor",
        "into a star",
        "on the set",
        "a solo dancer",
        "street corner",
        "it does not slide",
        "rotten salad",
        "neither nor",
        "the old location",
        "inside the area",
        "it still does",
        "short distance",
        "stand tall",
        "tell a tale",
        "it is not all",
        "his chores",
        "not a cheater",
        "he did it all",
        "eaten cheese",
        "cheers to all",
        "cheerleader",
        "charcoal",
        "chocolate",
        "eat carrots",
        "locate the car",
        "cold season",
        "dislocated",
        "dishonest",
        "it is not set",
        "set in stone",
        "all the seats",
        "his old tools",
        "as she said",
        "send a letter",
        "one sheet",
        "eastern sea",
        "earn a raise",
        "did not earn it",
        "it is rational",
        "one anchor",
        "sector three",
        "iron throne",
        "a lit candle",
        "noticed a detail",
        "do it at noon", 
        "scan his id",
        "not on earth",
        "drain the ale",
        "set the record",
        "a radical stance",
        "she has red hair",
        "loot crates",
        "cool clothes",
        "not in acid",
        "it is drastic",
        "hold on to it",
        "she reacted",
        "clean slate",
        "there is a hint",
        "a dart in the air",
        "there is a shrine",
        "to start a riot",
        "his landlord",
        "she can soar",
        "their dad sees",
        "the search is done",
        "did not search",
        "nodes not notes",
    )
}




